### ISSUE TITLE
RTL problem in post card

### ISSUE THREAD

**Issue by mskf1383** [Plume-org/Plume#858]
Post preview of RTL posts are like this:
![Screenshot from 2021-09-21 10-48-07](https://user-images.githubusercontent.com/50908329/134121417-479312b0-67a5-4b6d-be01-c35d9d7e418b.png)

I do some template change with my browser inspect element and make that:
![Screenshot from 2021-09-21 10-47-43](https://user-images.githubusercontent.com/50908329/134122301-bb25e377-da75-490d-b1b0-49a15fea917d.png)

HTML:
```html
<header>
    <div class="controls">
         <a class="button" href="/~/Tessssssssssssssssssst/test/edit">Edit</a>
     </div>
        <h3 class="p-name" dir="auto">
            <a class="u-url" href="/~/Tessssssssssssssssssst/test">
                test
            </a>
        </h3>
</header>
```

I move `div` under `h3` and move `dir="auto"` from `h3` to `header`:
```html
<header dir="auto">
        <h3 class="p-name">
            <a class="u-url" href="/~/Tessssssssssssssssssst/test">
                test
            </a>
        </h3>
    <div class="controls">
         <a class="button" href="/~/Tessssssssssssssssssst/test/edit">Edit</a>
     </div>
</header>
```

CSS:
```css
.card h3 {
    flex-grow: 1;
    margin: 0;
    font-family: "Vazir","Playfair Display",serif;
    font-size: 1.75em;
    font-weight: normal;
    line-height: 1.75;
    display: inline-block; /* New */
}
.card .controls {
    float: inline-end; /* Changed */
}
.card main {
    font-family: "Vazir","Lora",serif;
    font-size: 1em;
    line-height: 1.25;
    text-align: initial; /* Changed */
}
```

Good luck
