### ISSUE TITLE
plume docker postgres auth fails 

### ISSUE THREAD

**Issue by timconsidine** [Plume-org/Plume#859]
trying to install plume via docker following instructions
database cannot connect
```
root@xxxxxxxxxxxxx:~/plume# docker-compose run --rm plume plm migration run
Creating plume_plume_run ... done
Configuration read from /app/.env
thread 'main' panicked at 'Couldn't connect to the database.: BadConnection("FATAL:  password authentication failed for user \"plume\"\n")', plume-cli/src/main.rs:35:40
```

Refers to `/app/.env` but `docker exec -it <container> bash` reveals no file .env or directory /app

**Comment by KitaitiMakoto** [comment]
Can you paste the result of `ls -al` and your `docker-compose.yml`?

**Comment by timconsidine** [comment]
ls -al
```
drwxr-xr-x  4 root root 4096 Oct  5 12:47 .
drwx------ 13 root root 4096 Oct  5 12:38 ..
-rw-r--r--  1 root root  539 Oct  5 12:58 .env
-rw-r--r--  1 root root  488 Oct  5 12:47 .env.example
drwxr-xr-x  4 root root 4096 Oct  5 12:44 data
-rw-r--r--  1 root root  466 Oct  5 13:11 docker-compose.yml
drwxr-xr-x  2 root root 4096 Oct  5 12:44 search_index
```

**Comment by timconsidine** [comment]
docker-compose.yaml :
```
version: '3'

services:
  postgres:
    image: postgres:10.5
    env_file: .env
    restart: unless-stopped
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
  plume:
    image: plumeorg/plume:latest
    env_file: .env
    restart: unless-stopped
    volumes:
      - "./data/plume/static/media:/app/static/media"
      - "./.env:/app/.env"
      - "./search_index:/app/search_index"
    ports:
      - "127.0.0.1:7878:7878"
```
